version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a"
    - "< 15"
