sudo: required
dist: xenial

notifications:
  email: false

language: node_js
node_js:
  - '12'

git:
  submodules: true

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

install:
  - docker exec -it emscripten npm i -g yarn
  - yarn

script:
  - yarn lint
  - docker exec -it emscripten yarn build
